### ISSUE TITLE
Add storageClass configuration in the helm chart

### ISSUE THREAD

**Issue by alemax22** [pegasystems/pega-helm-charts#439]
**Describe the bug**
We are not able to pass a custom storage class for the search volumeClaim and our volume claim systems needs this configuration parameter. This prevents us from deploying the cluster to our current productive Kubernetes environment.

**To Reproduce**
Try Deploying cluster with custom volumeClaim for the search pod.

**Expected behavior**
Expose the configuration of the volumeClaim class for the search pods in the helm chart

**Chart version**
v2.1.1

**Server (if applicable, please complete the following information):**
 - OS: Ubuntu 18.04
 - Environment: Open Source Kubernetes 1.22
 - Database:  PostgreSQL

**Additional context**
None

**Comment by RyanStan** [comment]
Thanks for bringing this up Alessandro, we'll add this

**Comment by maracle6** [comment]
This would also be useful for pega tiers, for Stream or in case any other volume claim is required for some reason.

**Comment by arvasrikanth** [comment]
The use case was addressed in [ISSUE-439](https://github.com/pegasystems/pega-helm-charts/pull/473)

**Comment by alemax22** [comment]
The issue is still present in the v.3.1.0 chart, have you added the possibility to change the storage class of the volume claims associated to the search pod?

**Comment by maracle6** [comment]
You should be able to configure it using the storageClassName element.

https://github.com/pegasystems/pega-helm-charts/blob/28937d96ebb2383fd5e57b9f6d3e727b3e3177d9/charts/pega/values.yaml#L29

**Comment by arvasrikanth** [comment]
> The issue is still present in the v.3.1.0 chart, have you added the possibility to change the storage class of the volume claims associated to the search pod?

Yes

**Comment by alemax22** [comment]
Ok, thank you, and where is the right place to set the storage size for the search pods?
because the: volumeClaimTemplate.resources.requests.storage under the pegasearch part of the chart is not working...
